export const SENSITIVE_TOOL_IDS = [
  "send-email",
  "delete-email",
  "create-event",
  "delete-event",
  "delete-file",
  "write-sheet",
  "share-file",
  "send-chat-message",
  "create-reaction",
  "create-doc",
  "batch-update-doc",
  "export-doc-to-pdf",
  "insert-doc-image",
  "find-and-replace-doc",
  "update-paragraph-style",
  "update-doc-headers-footers",
  "create-table-with-data",
  "modify-sheet-values",
  "append-sheet-values",
  "create-sheet",
  "batch-update-sheet",
  "format-sheet-range",
  "move-sheet-rows",
  "resize-sheet-dimensions",
  "manage-conditional-formatting",
  "create-drive-file",
  "create-drive-folder",
  "import-drive-file",
  "set-drive-permissions",
  "delete-drive-file",
  "copy-drive-file",
  "update-drive-file",
  "create-document",
  "create-calendar",
  "manage-out-of-office",
  "manage-focus-time",
  "create-contact",
  "manage-contact",
  "manage-contacts-batch",
  "manage-contact-group",
  // Microsoft (Outlook/OneDrive)
  "reply-outlook-email",
  "send-outlook-draft",
  "move-outlook-messages",
  "create-outlook-rule",
  "create-outlook-category",
  "delete-outlook-category",
  "apply-outlook-categories",
  "remove-outlook-categories",
  "update-outlook-event",
  "delete-outlook-event",
  "upload-one-drive-file",
  "delete-one-drive-item",
  "share-one-drive-item",
  "move-one-drive-item",
  "create-outlook-contact",
  "update-outlook-contact",
  "delete-outlook-contact",
  "delete-todo-list",
  "create-todo-task",
  "update-todo-task",
  "delete-todo-task",
  "add-todo-checklist-item",
  "update-todo-checklist-item",
] as const;

export const NON_SENSITIVE_TOOL_IDS = [
  "read-emails",
  "read-calendar",
  "search-drive",
  "read-sheet",
  "search-docs",
  "get-doc-content",
  "get-doc-as-markdown",
  "list-docs-in-folder",
  "list-doc-comments",
  "list-spreadsheets",
  "get-spreadsheet-info",
  "list-sheet-tables",
  "list-sheet-comments",
  "list-drawings",
  "list-chat-spaces",
  "get-chat-messages",
  "search-chat-messages",
  "get-form",
  "list-form-responses",
  "get-form-response",
  "list-task-lists",
  "get-task-list",
  "list-tasks",
  "get-task",
  "list-contacts",
  "get-contact",
  "search-contacts",
  "list-contact-groups",
  "get-contact-group",
  "read-outlook-emails",
  "read-outlook-calendar",
  "search-one-drive",
  "read-one-drive-file",
  "read-drive-file-content",
  "get-drive-download-url",
  "get-drive-permissions",
  "check-drive-public-access",
  "list-drive-items",
  "get-drive-file-content",
  "get-drive-download-url",
  "list-calendars",
  "get-events",
  "query-freebusy",
  // Microsoft (Outlook/OneDrive) — reads and drafts
  "read-outlook-message",
  "get-outlook-attachment",
  "draft-outlook-reply-all",
  "draft-outlook-email",
  "update-outlook-draft",
  "list-outlook-drafts",
  "search-outlook-messages",
  "list-outlook-folders",
  "create-outlook-folder",
  "list-outlook-rules",
  "get-outlook-focused-inbox",
  "list-outlook-categories",
  "update-outlook-category",
  "get-outlook-event",
  "search-one-drive-all",
  "list-one-drive-items",
  "get-one-drive-item",
  "download-one-drive-file",
  "copy-one-drive-item",
  "create-one-drive-folder",
  "search-m365",
  "list-outlook-contacts",
  "search-outlook-contacts",
  "get-outlook-contact",
  "list-outlook-contact-folders",
  "create-outlook-contact-folder",
  "list-todo-lists",
  "create-todo-list",
  "get-todo-list",
  "update-todo-list",
  "list-todo-tasks",
  "get-todo-task",
  "list-todo-checklist",
] as const;

/** The agent tool names as registered in the chat agent. */
export const AGENT_TOOL_NAMES = [
  // Gmail
  "readEmails",
  "sendEmail",
  "searchGmailMessages",
  "getGmailMessage",
  "getGmailMessagesBatch",
  "getGmailAttachment",
  "getGmailThread",
  "getGmailThreadsBatch",
  "modifyGmailLabels",
  "batchModifyGmailLabels",
  "listGmailLabels",
  "manageGmailLabel",
  "draftGmailMessage",
  "listGmailFilters",
  "manageGmailFilter",
  // Drive
  "searchDrive",
  "getDriveFileContent",
  "getDriveDownloadUrl",
  "createDriveFile",
  "createDriveFolder",
  "importDriveFile",
  "getDriveShareableLink",
  "listDriveItems",
  "copyDriveFile",
  "updateDriveFile",
  "deleteDriveFile",
  "getDrivePermissions",
  "setDrivePermissions",
  "checkDrivePublicAccess",
  // Calendar
  "readCalendar",
  "createEvent",
  "listCalendars",
  "getEvents",
  "updateEvent",
  "deleteEvent",
  "createCalendar",
  "queryFreebusy",
  "manageOutOfOffice",
  "manageFocusTime",
  // Sheets
  "readSheet",
  "createSpreadsheet",
  "listSpreadsheets",
  "getSpreadsheetInfo",
  "modifySheetValues",
  "appendSheetValues",
  "createSheet",
  "batchUpdateSheet",
  "listSheetTables",
  "listSheetComments",
  "formatSheetRange",
  "moveSheetRows",
  "resizeSheetDimensions",
  "manageConditionalFormatting",
  // Docs
  "searchDocs",
  "getDocContent",
  "getDocAsMarkdown",
  "createDoc",
  "batchUpdateDoc",
  "exportDocToPdf",
  "listDocsInFolder",
  "listDocComments",
  "insertDocImage",
  "findAndReplaceDoc",
  "updateParagraphStyle",
  "updateDocHeadersFooters",
  "inspectDocStructure",
  "createTableWithData",
  "convertFileToGoogleDoc",
  "readPdfContent",
  // Slides
  "createPresentation",
  "getPresentation",
  "batchUpdatePresentation",
  "getPage",
  "getPageThumbnail",
  "listPresentationComments",
  // Forms
  "createForm",
  "getForm",
  "batchUpdateForm",
  "listFormResponses",
  "getFormResponse",
  "setPublishSettings",
  // Tasks
  "listTaskLists",
  "getTaskList",
  "manageTaskList",
  "listTasks",
  "getTask",
  "manageTask",
  // Contacts
  "listContacts",
  "getContact",
  "searchContacts",
  "manageContact",
  "manageContactsBatch",
  "listContactGroups",
  "getContactGroup",
  "manageContactGroup",
  // Chat
  "listChatSpaces",
  "getChatMessages",
  "sendChatMessage",
  "searchChatMessages",
  "createChatReation",
  // Microsoft (Outlook/OneDrive)
  "readOutlookEmails",
  "sendOutlookEmail",
  "readOutlookMessage",
  "getOutlookAttachment",
  "replyOutlookEmail",
  "draftOutlookReplyAll",
  "draftOutlookEmail",
  "updateOutlookDraft",
  "sendOutlookDraft",
  "listOutlookDrafts",
  "searchOutlookMessages",
  "moveOutlookMessages",
  "listOutlookFolders",
  "createOutlookFolder",
  "listOutlookRules",
  "createOutlookRule",
  "getOutlookFocusedInbox",
  "listOutlookCategories",
  "createOutlookCategory",
  "updateOutlookCategory",
  "deleteOutlookCategory",
  "applyOutlookCategories",
  "removeOutlookCategories",
  "readOutlookCalendar",
  "createOutlookEvent",
  "getOutlookEvent",
  "updateOutlookEvent",
  "deleteOutlookEvent",
  "searchOneDrive",
  "searchOneDriveAll",
  "listOneDriveItems",
  "getOneDriveItem",
  "readOneDriveFile",
  "downloadOneDriveFile",
  "uploadOneDriveFile",
  "deleteOneDriveItem",
  "shareOneDriveItem",
  "moveOneDriveItem",
  "copyOneDriveItem",
  "createOneDriveFolder",
  "searchM365",
  "listOutlookContacts",
  "searchOutlookContacts",
  "getOutlookContact",
  "createOutlookContact",
  "updateOutlookContact",
  "deleteOutlookContact",
  "listOutlookContactFolders",
  "createOutlookContactFolder",
  "listTodoLists",
  "createTodoList",
  "getTodoList",
  "updateTodoList",
  "deleteTodoList",
  "listTodoTasks",
  "createTodoTask",
  "getTodoTask",
  "updateTodoTask",
  "deleteTodoTask",
  "listTodoChecklist",
  "addTodoChecklistItem",
  "updateTodoChecklistItem",
  // Automation
  "scheduleTask",
  "createEventTrigger",
] as const;

export type AgentToolName = (typeof AGENT_TOOL_NAMES)[number];

/** Per-tool default sensitivity. Sensitive tools pause for doctor approval in chat. */
export const TOOL_SENSITIVITY_DEFAULTS: Record<AgentToolName, boolean> = {
  // Gmail
  readEmails: false,
  sendEmail: true,
  searchGmailMessages: false,
  getGmailMessage: false,
  getGmailMessagesBatch: false,
  getGmailAttachment: false,
  getGmailThread: false,
  getGmailThreadsBatch: false,
  modifyGmailLabels: true,
  batchModifyGmailLabels: true,
  listGmailLabels: false,
  manageGmailLabel: true,
  draftGmailMessage: true,
  listGmailFilters: false,
  manageGmailFilter: true,
  // Drive
  searchDrive: false,
  getDriveFileContent: false,
  getDriveDownloadUrl: false,
  createDriveFile: true,
  createDriveFolder: true,
  importDriveFile: true,
  getDriveShareableLink: true,
  listDriveItems: false,
  copyDriveFile: true,
  updateDriveFile: true,
  deleteDriveFile: true,
  getDrivePermissions: false,
  setDrivePermissions: true,
  checkDrivePublicAccess: false,
  // Calendar
  readCalendar: false,
  createEvent: true,
  listCalendars: false,
  getEvents: false,
  updateEvent: true,
  deleteEvent: true,
  createCalendar: true,
  queryFreebusy: false,
  manageOutOfOffice: true,
  manageFocusTime: true,
  // Sheets
  readSheet: false,
  createSpreadsheet: true,
  listSpreadsheets: false,
  getSpreadsheetInfo: false,
  modifySheetValues: true,
  appendSheetValues: true,
  createSheet: true,
  batchUpdateSheet: true,
  listSheetTables: false,
  listSheetComments: false,
  formatSheetRange: true,
  moveSheetRows: true,
  resizeSheetDimensions: true,
  manageConditionalFormatting: true,
  // Docs
  searchDocs: false,
  getDocContent: false,
  getDocAsMarkdown: false,
  createDoc: true,
  batchUpdateDoc: true,
  exportDocToPdf: true,
  listDocsInFolder: false,
  listDocComments: false,
  insertDocImage: true,
  findAndReplaceDoc: true,
  updateParagraphStyle: true,
  updateDocHeadersFooters: true,
  inspectDocStructure: false,
  createTableWithData: true,
  convertFileToGoogleDoc: true,
  readPdfContent: false,
  // Slides
  createPresentation: true,
  getPresentation: false,
  batchUpdatePresentation: true,
  getPage: false,
  getPageThumbnail: false,
  listPresentationComments: false,
  // Forms
  createForm: true,
  getForm: false,
  batchUpdateForm: true,
  listFormResponses: false,
  getFormResponse: false,
  setPublishSettings: true,
  // Tasks
  listTaskLists: false,
  getTaskList: false,
  manageTaskList: true,
  listTasks: false,
  getTask: false,
  manageTask: true,
  // Contacts
  listContacts: false,
  getContact: false,
  searchContacts: false,
  manageContact: true,
  manageContactsBatch: true,
  listContactGroups: false,
  getContactGroup: false,
  manageContactGroup: true,
  // Chat
  listChatSpaces: false,
  getChatMessages: false,
  sendChatMessage: true,
  searchChatMessages: false,
  createChatReation: true,
  // Microsoft (Outlook/OneDrive)
  readOutlookEmails: false,
  sendOutlookEmail: true,
  readOutlookMessage: false,
  getOutlookAttachment: false,
  replyOutlookEmail: true,
  draftOutlookReplyAll: false,
  draftOutlookEmail: false,
  updateOutlookDraft: false,
  sendOutlookDraft: true,
  listOutlookDrafts: false,
  searchOutlookMessages: false,
  moveOutlookMessages: true,
  listOutlookFolders: false,
  createOutlookFolder: false,
  listOutlookRules: false,
  createOutlookRule: true,
  getOutlookFocusedInbox: false,
  listOutlookCategories: false,
  createOutlookCategory: true,
  updateOutlookCategory: false,
  deleteOutlookCategory: true,
  applyOutlookCategories: true,
  removeOutlookCategories: true,
  readOutlookCalendar: false,
  createOutlookEvent: true,
  getOutlookEvent: false,
  updateOutlookEvent: true,
  deleteOutlookEvent: true,
  searchOneDrive: false,
  searchOneDriveAll: false,
  listOneDriveItems: false,
  getOneDriveItem: false,
  readOneDriveFile: false,
  downloadOneDriveFile: false,
  uploadOneDriveFile: true,
  deleteOneDriveItem: true,
  shareOneDriveItem: true,
  moveOneDriveItem: true,
  copyOneDriveItem: false,
  createOneDriveFolder: false,
  searchM365: false,
  listOutlookContacts: false,
  searchOutlookContacts: false,
  getOutlookContact: false,
  createOutlookContact: true,
  updateOutlookContact: true,
  deleteOutlookContact: true,
  listOutlookContactFolders: false,
  createOutlookContactFolder: false,
  listTodoLists: false,
  createTodoList: false,
  getTodoList: false,
  updateTodoList: false,
  deleteTodoList: true,
  listTodoTasks: false,
  createTodoTask: true,
  getTodoTask: false,
  updateTodoTask: true,
  deleteTodoTask: true,
  listTodoChecklist: false,
  addTodoChecklistItem: true,
  updateTodoChecklistItem: true,
  // Automation
  scheduleTask: false,
  createEventTrigger: false,
};

/** Automation kinds that can carry per-automation tool overrides. */
export const AUTOMATION_TYPES = ["scheduled_task", "event_trigger"] as const;
export type AutomationType = (typeof AUTOMATION_TYPES)[number];

/**
 * Map every agent tool to the snake_case `action_type` used on
 * `approval_requests`. The four side-effect tools were the only ones that
 * previously created approvals; the rest are added so the unified automation
 * sensitivity gate (override -> general -> default) can pause on any tool.
 */
export const TOOL_ACTION_TYPES: Record<AgentToolName, string> = {
  // Gmail
  readEmails: "read_emails",
  sendEmail: "send_email",
  searchGmailMessages: "search_gmail_messages",
  getGmailMessage: "get_gmail_message",
  getGmailMessagesBatch: "get_gmail_messages_batch",
  getGmailAttachment: "get_gmail_attachment",
  getGmailThread: "get_gmail_thread",
  getGmailThreadsBatch: "get_gmail_messages_batch",
  modifyGmailLabels: "modify_gmail_labels",
  batchModifyGmailLabels: "batch_modify_gmail_labels",
  listGmailLabels: "list_gmail_labels",
  manageGmailLabel: "manage_gmail_label",
  draftGmailMessage: "draft_gmail_message",
  listGmailFilters: "list_gmail_filters",
  manageGmailFilter: "manage_gmail_filter",
  // Drive
  searchDrive: "search_drive",
  getDriveFileContent: "get_drive_file_content",
  getDriveDownloadUrl: "get_drive_download_url",
  createDriveFile: "create_drive_file",
  createDriveFolder: "create_drive_folder",
  importDriveFile: "import_drive_file",
  getDriveShareableLink: "get_drive_shareable_link",
  listDriveItems: "list_drive_items",
  copyDriveFile: "copy_drive_file",
  updateDriveFile: "update_drive_file",
  deleteDriveFile: "delete_drive_file",
  getDrivePermissions: "get_drive_permissions",
  setDrivePermissions: "set_drive_permissions",
  checkDrivePublicAccess: "check_drive_public_access",
  // Calendar
  readCalendar: "read_calendar",
  createEvent: "create_event",
  listCalendars: "list_calendars",
  getEvents: "get_events",
  updateEvent: "update_event",
  deleteEvent: "delete_event",
  createCalendar: "create_calendar",
  queryFreebusy: "query_freebusy",
  manageOutOfOffice: "manage_out_of_office",
  manageFocusTime: "manage_focus_time",
  // Sheets
  readSheet: "read_sheet",
  createSpreadsheet: "create_spreadsheet",
  listSpreadsheets: "list_spreadsheets",
  getSpreadsheetInfo: "get_spreadsheet_info",
  modifySheetValues: "modify_sheet_values",
  appendSheetValues: "append_sheet_values",
  createSheet: "create_sheet",
  batchUpdateSheet: "batch_update_sheet",
  listSheetTables: "list_sheet_tables",
  listSheetComments: "list_sheet_comments",
  formatSheetRange: "format_sheet_range",
  moveSheetRows: "move_sheet_rows",
  resizeSheetDimensions: "resize_sheet_dimensions",
  manageConditionalFormatting: "manage_conditional_formatting",
  // Docs
  searchDocs: "search_docs",
  getDocContent: "get_doc_content",
  getDocAsMarkdown: "get_doc_as_markdown",
  createDoc: "create_doc",
  batchUpdateDoc: "batch_update_doc",
  exportDocToPdf: "export_doc_to_pdf",
  listDocsInFolder: "list_docs_in_folder",
  listDocComments: "list_doc_comments",
  insertDocImage: "insert_doc_image",
  findAndReplaceDoc: "find_and_replace_doc",
  updateParagraphStyle: "update_paragraph_style",
  updateDocHeadersFooters: "update_doc_headers_footers",
  inspectDocStructure: "inspect_doc_structure",
  createTableWithData: "create_table_with_data",
  convertFileToGoogleDoc: "convert_file_to_google_doc",
  readPdfContent: "read_pdf_content",
  // Slides
  createPresentation: "create_presentation",
  getPresentation: "get_presentation",
  batchUpdatePresentation: "batch_update_presentation",
  getPage: "get_page",
  getPageThumbnail: "get_page_thumbnail",
  listPresentationComments: "list_presentation_comments",
  // Forms
  createForm: "create_form",
  getForm: "get_form",
  batchUpdateForm: "batch_update_form",
  listFormResponses: "list_form_responses",
  getFormResponse: "get_form_response",
  setPublishSettings: "set_publish_settings",
  // Tasks
  listTaskLists: "list_task_lists",
  getTaskList: "get_task_list",
  manageTaskList: "manage_task_list",
  listTasks: "list_tasks",
  getTask: "get_task",
  manageTask: "manage_task",
  // Contacts
  listContacts: "list_contacts",
  getContact: "get_contact",
  searchContacts: "search_contacts",
  manageContact: "manage_contact",
  manageContactsBatch: "manage_contacts_batch",
  listContactGroups: "list_contact_groups",
  getContactGroup: "get_contact_group",
  manageContactGroup: "manage_contact_group",
  // Chat
  listChatSpaces: "list_chat_spaces",
  getChatMessages: "get_chat_messages",
  sendChatMessage: "send_chat_message",
  searchChatMessages: "search_chat_messages",
  createChatReation: "create_chat_reaction",
  // Microsoft (Outlook/OneDrive)
  readOutlookEmails: "read_outlook_emails",
  sendOutlookEmail: "send_outlook_email",
  readOutlookMessage: "read_outlook_message",
  getOutlookAttachment: "get_outlook_attachment",
  replyOutlookEmail: "reply_outlook_email",
  draftOutlookReplyAll: "draft_outlook_reply_all",
  draftOutlookEmail: "draft_outlook_email",
  updateOutlookDraft: "update_outlook_draft",
  sendOutlookDraft: "send_outlook_draft",
  listOutlookDrafts: "list_outlook_drafts",
  searchOutlookMessages: "search_outlook_messages",
  moveOutlookMessages: "move_outlook_messages",
  listOutlookFolders: "list_outlook_folders",
  createOutlookFolder: "create_outlook_folder",
  listOutlookRules: "list_outlook_rules",
  createOutlookRule: "create_outlook_rule",
  getOutlookFocusedInbox: "get_outlook_focused_inbox",
  listOutlookCategories: "list_outlook_categories",
  createOutlookCategory: "create_outlook_category",
  updateOutlookCategory: "update_outlook_category",
  deleteOutlookCategory: "delete_outlook_category",
  applyOutlookCategories: "apply_outlook_categories",
  removeOutlookCategories: "remove_outlook_categories",
  readOutlookCalendar: "read_outlook_calendar",
  createOutlookEvent: "create_outlook_event",
  getOutlookEvent: "get_outlook_event",
  updateOutlookEvent: "update_outlook_event",
  deleteOutlookEvent: "delete_outlook_event",
  searchOneDrive: "search_one_drive",
  searchOneDriveAll: "search_one_drive_all",
  listOneDriveItems: "list_one_drive_items",
  getOneDriveItem: "get_one_drive_item",
  readOneDriveFile: "read_one_drive_file",
  downloadOneDriveFile: "download_one_drive_file",
  uploadOneDriveFile: "upload_one_drive_file",
  deleteOneDriveItem: "delete_one_drive_item",
  shareOneDriveItem: "share_one_drive_item",
  moveOneDriveItem: "move_one_drive_item",
  copyOneDriveItem: "copy_one_drive_item",
  createOneDriveFolder: "create_one_drive_folder",
  searchM365: "search_m365",
  listOutlookContacts: "list_outlook_contacts",
  searchOutlookContacts: "search_outlook_contacts",
  getOutlookContact: "get_outlook_contact",
  createOutlookContact: "create_outlook_contact",
  updateOutlookContact: "update_outlook_contact",
  deleteOutlookContact: "delete_outlook_contact",
  listOutlookContactFolders: "list_outlook_contact_folders",
  createOutlookContactFolder: "create_outlook_contact_folder",
  listTodoLists: "list_todo_lists",
  createTodoList: "create_todo_list",
  getTodoList: "get_todo_list",
  updateTodoList: "update_todo_list",
  deleteTodoList: "delete_todo_list",
  listTodoTasks: "list_todo_tasks",
  createTodoTask: "create_todo_task",
  getTodoTask: "get_todo_task",
  updateTodoTask: "update_todo_task",
  deleteTodoTask: "delete_todo_task",
  listTodoChecklist: "list_todo_checklist",
  addTodoChecklistItem: "add_todo_checklist_item",
  updateTodoChecklistItem: "update_todo_checklist_item",
  // Automation
  scheduleTask: "schedule_task",
  createEventTrigger: "create_event_trigger",
};