import type { AgentToolName } from "@repo/shared";

export interface ToolDescriptor {
  name: AgentToolName;
  label: string;
  description: string;
}

export const TOOL_DESCRIPTORS: ToolDescriptor[] = [
  // Gmail
  { name: "readEmails", label: "Read Gmail", description: "Read the latest emails from Gmail" },
  { name: "sendEmail", label: "Send Gmail", description: "Send an email from the doctor's Gmail account" },
  { name: "searchGmailMessages", label: "Search Gmail Messages", description: "Search for messages in Gmail with query filters" },
  { name: "getGmailMessage", label: "Get Gmail Message", description: "Get a single Gmail message by ID" },
  { name: "getGmailMessagesBatch", label: "Get Gmail Messages Batch", description: "Get multiple Gmail messages by IDs" },
  { name: "getGmailAttachment", label: "Get Gmail Attachment", description: "Download an attachment from a Gmail message" },
  { name: "getGmailThread", label: "Get Gmail Thread", description: "Get a Gmail thread by ID" },
  { name: "getGmailThreadsBatch", label: "Get Gmail Threads Batch", description: "Get multiple Gmail threads by IDs" },
  { name: "modifyGmailLabels", label: "Modify Gmail Labels", description: "Add or remove labels on a Gmail message" },
  { name: "batchModifyGmailLabels", label: "Batch Modify Gmail Labels", description: "Add or remove labels on multiple Gmail messages" },
  { name: "listGmailLabels", label: "List Gmail Labels", description: "List all Gmail labels" },
  { name: "manageGmailLabel", label: "Manage Gmail Label", description: "Create, update, or delete a Gmail label" },
  { name: "draftGmailMessage", label: "Draft Gmail Message", description: "Create a draft email in Gmail" },
  { name: "listGmailFilters", label: "List Gmail Filters", description: "List all Gmail filters" },
  { name: "manageGmailFilter", label: "Manage Gmail Filter", description: "Create, update, or delete a Gmail filter" },
  // Drive
  { name: "searchDrive", label: "Search Google Drive", description: "Search for files in the doctor's Google Drive" },
  { name: "getDriveFileContent", label: "Get Drive File Content", description: "Get the content of a file in Google Drive" },
  { name: "getDriveDownloadUrl", label: "Get Drive Download URL", description: "Get a download URL for a file in Google Drive" },
  { name: "createDriveFile", label: "Create Drive File", description: "Create a new file in Google Drive" },
  { name: "createDriveFolder", label: "Create Drive Folder", description: "Create a new folder in Google Drive" },
  { name: "importDriveFile", label: "Import Drive File", description: "Import a file into Google Drive" },
  { name: "getDriveShareableLink", label: "Get Drive Shareable Link", description: "Get a shareable link for a file in Google Drive" },
  { name: "listDriveItems", label: "List Drive Items", description: "List files and folders in Google Drive" },
  { name: "copyDriveFile", label: "Copy Drive File", description: "Copy a file in Google Drive" },
  { name: "updateDriveFile", label: "Update Drive File", description: "Update a file's metadata or content in Google Drive" },
  { name: "deleteDriveFile", label: "Delete Drive File", description: "Delete a file from Google Drive" },
  { name: "getDrivePermissions", label: "Get Drive Permissions", description: "Get permissions for a file in Google Drive" },
  { name: "setDrivePermissions", label: "Set Drive Permissions", description: "Set permissions for a file in Google Drive" },
  { name: "checkDrivePublicAccess", label: "Check Drive Public Access", description: "Check if a file in Google Drive is publicly accessible" },
  // Calendar
  { name: "readCalendar", label: "Read Google Calendar", description: "Read events from the doctor's Google Calendar" },
  { name: "createEvent", label: "Create Google Calendar Event", description: "Create a Google Calendar event (may invite attendees)" },
  { name: "listCalendars", label: "List Calendars", description: "List all calendars in Google Calendar" },
  { name: "getEvents", label: "Get Calendar Events", description: "Get events from Google Calendar within a date range" },
  { name: "updateEvent", label: "Update Calendar Event", description: "Update an event in Google Calendar" },
  { name: "deleteEvent", label: "Delete Calendar Event", description: "Delete an event from Google Calendar" },
  { name: "createCalendar", label: "Create Calendar", description: "Create a new calendar in Google Calendar" },
  { name: "queryFreebusy", label: "Query Free/Busy", description: "Query free/busy status for calendars" },
  { name: "manageOutOfOffice", label: "Manage Out of Office", description: "Manage out of office settings in Google Calendar" },
  { name: "manageFocusTime", label: "Manage Focus Time", description: "Manage focus time settings in Google Calendar" },
  // Sheets
  { name: "readSheet", label: "Read Google Sheets", description: "Read data from a Google Sheet" },
  { name: "createSpreadsheet", label: "Create Spreadsheet", description: "Create a new Google Spreadsheet" },
  { name: "listSpreadsheets", label: "List Spreadsheets", description: "List all Google Spreadsheets" },
  { name: "getSpreadsheetInfo", label: "Get Spreadsheet Info", description: "Get information about a Google Spreadsheet" },
  { name: "modifySheetValues", label: "Modify Sheet Values", description: "Modify values in a Google Sheet" },
  { name: "appendSheetValues", label: "Append Sheet Values", description: "Append values to a Google Sheet" },
  { name: "createSheet", label: "Create Sheet", description: "Create a new sheet in a Google Spreadsheet" },
  { name: "batchUpdateSheet", label: "Batch Update Sheet", description: "Batch update a Google Spreadsheet" },
  { name: "listSheetTables", label: "List Sheet Tables", description: "List tables in a Google Sheet" },
  { name: "listSheetComments", label: "List Sheet Comments", description: "List comments in a Google Sheet" },
  { name: "formatSheetRange", label: "Format Sheet Range", description: "Format a range in a Google Sheet" },
  { name: "moveSheetRows", label: "Move Sheet Rows", description: "Move rows in a Google Sheet" },
  { name: "resizeSheetDimensions", label: "Resize Sheet Dimensions", description: "Resize rows/columns in a Google Sheet" },
  { name: "manageConditionalFormatting", label: "Manage Conditional Formatting", description: "Manage conditional formatting rules in a Google Sheet" },
  // Docs
  { name: "searchDocs", label: "Search Google Docs", description: "Search for documents in Google Drive" },
  { name: "getDocContent", label: "Get Doc Content", description: "Get the content of a Google Doc" },
  { name: "getDocAsMarkdown", label: "Get Doc as Markdown", description: "Get a Google Doc as Markdown" },
  { name: "createDoc", label: "Create Doc", description: "Create a new Google Doc" },
  { name: "batchUpdateDoc", label: "Batch Update Doc", description: "Batch update a Google Doc" },
  { name: "exportDocToPdf", label: "Export Doc to PDF", description: "Export a Google Doc to PDF" },
  { name: "listDocsInFolder", label: "List Docs in Folder", description: "List Google Docs in a folder" },
  { name: "listDocComments", label: "List Doc Comments", description: "List comments in a Google Doc" },
  { name: "insertDocImage", label: "Insert Doc Image", description: "Insert an image into a Google Doc" },
  { name: "findAndReplaceDoc", label: "Find and Replace in Doc", description: "Find and replace text in a Google Doc" },
  { name: "updateParagraphStyle", label: "Update Paragraph Style", description: "Update paragraph style in a Google Doc" },
  { name: "updateDocHeadersFooters", label: "Update Doc Headers/Footers", description: "Update headers and footers in a Google Doc" },
  { name: "inspectDocStructure", label: "Inspect Doc Structure", description: "Inspect the structure of a Google Doc" },
  { name: "createTableWithData", label: "Create Table with Data", description: "Create a table with data in a Google Doc" },
  { name: "convertFileToGoogleDoc", label: "Convert File to Google Doc", description: "Convert an uploaded .docx (or other Office file) into a native Google Doc" },
  { name: "readPdfContent", label: "Read PDF Content", description: "Extract text from a PDF file directly, without converting it to Google Docs" },
  // Slides
  { name: "createPresentation", label: "Create Presentation", description: "Create a new Google Slides presentation" },
  { name: "getPresentation", label: "Get Presentation", description: "Get a Google Slides presentation" },
  { name: "batchUpdatePresentation", label: "Batch Update Presentation", description: "Batch update a Google Slides presentation" },
  { name: "getPage", label: "Get Slide", description: "Get a slide from a Google Slides presentation" },
  { name: "getPageThumbnail", label: "Get Slide Thumbnail", description: "Get a thumbnail of a slide from Google Slides" },
  { name: "listPresentationComments", label: "List Presentation Comments", description: "List comments in a Google Slides presentation" },
  // Forms
  { name: "createForm", label: "Create Form", description: "Create a new Google Form" },
  { name: "getForm", label: "Get Form", description: "Get a Google Form" },
  { name: "batchUpdateForm", label: "Batch Update Form", description: "Batch update a Google Form" },
  { name: "listFormResponses", label: "List Form Responses", description: "List responses to a Google Form" },
  { name: "getFormResponse", label: "Get Form Response", description: "Get a single response from a Google Form" },
  { name: "setPublishSettings", label: "Set Form Publish Settings", description: "Set publish settings for a Google Form" },
  // Tasks
  { name: "listTaskLists", label: "List Task Lists", description: "List Google Task lists" },
  { name: "getTaskList", label: "Get Task List", description: "Get a Google Task list" },
  { name: "manageTaskList", label: "Manage Task List", description: "Create, update, or delete a Google Task list" },
  { name: "listTasks", label: "List Tasks", description: "List tasks in a Google Task list" },
  { name: "getTask", label: "Get Task", description: "Get a Google Task" },
  { name: "manageTask", label: "Manage Task", description: "Create, update, or delete a Google Task" },
  // Contacts
  { name: "listContacts", label: "List Contacts", description: "List Google Contacts" },
  { name: "getContact", label: "Get Contact", description: "Get a Google Contact" },
  { name: "searchContacts", label: "Search Contacts", description: "Search Google Contacts" },
  { name: "manageContact", label: "Manage Contact", description: "Create, update, or delete a Google Contact" },
  { name: "manageContactsBatch", label: "Manage Contacts Batch", description: "Batch create, update, or delete Google Contacts" },
  { name: "listContactGroups", label: "List Contact Groups", description: "List Google Contact groups" },
  { name: "getContactGroup", label: "Get Contact Group", description: "Get a Google Contact group" },
  { name: "manageContactGroup", label: "Manage Contact Group", description: "Create, update, or delete a Google Contact group" },
  // Chat
  { name: "listChatSpaces", label: "List Chat Spaces", description: "List Google Chat spaces" },
  { name: "getChatMessages", label: "Get Chat Messages", description: "Get messages from a Google Chat space" },
  { name: "sendChatMessage", label: "Send Chat Message", description: "Send a message to a Google Chat space" },
  { name: "searchChatMessages", label: "Search Chat Messages", description: "Search messages in Google Chat" },
  { name: "createChatReation", label: "Create Chat Reaction", description: "Create a reaction on a Google Chat message" },
  // Microsoft (Outlook/OneDrive)
  { name: "readOutlookEmails", label: "Read Outlook Email", description: "Read the latest emails from Outlook" },
  { name: "sendOutlookEmail", label: "Send Outlook Email", description: "Send an email from the doctor's Outlook account" },
  { name: "readOutlookMessage", label: "Read Outlook Message", description: "Read a single Outlook message by ID" },
  { name: "getOutlookAttachment", label: "Get Outlook Attachment", description: "Download an attachment from an Outlook message" },
  { name: "replyOutlookEmail", label: "Reply Outlook Email", description: "Reply to an Outlook email" },
  { name: "draftOutlookReplyAll", label: "Draft Outlook Reply All", description: "Create a reply-all draft in Outlook" },
  { name: "draftOutlookEmail", label: "Draft Outlook Email", description: "Create a draft email in Outlook" },
  { name: "updateOutlookDraft", label: "Update Outlook Draft", description: "Update an Outlook draft email" },
  { name: "sendOutlookDraft", label: "Send Outlook Draft", description: "Send an Outlook draft email" },
  { name: "listOutlookDrafts", label: "List Outlook Drafts", description: "List the doctor's Outlook drafts" },
  { name: "searchOutlookMessages", label: "Search Outlook Messages", description: "Search the doctor's Outlook messages" },
  { name: "moveOutlookMessages", label: "Move Outlook Messages", description: "Move Outlook messages between folders" },
  { name: "listOutlookFolders", label: "List Outlook Folders", description: "List the doctor's Outlook mail folders" },
  { name: "createOutlookFolder", label: "Create Outlook Folder", description: "Create a new Outlook mail folder" },
  { name: "listOutlookRules", label: "List Outlook Rules", description: "List the doctor's Outlook inbox rules" },
  { name: "createOutlookRule", label: "Create Outlook Rule", description: "Create an Outlook inbox rule" },
  { name: "getOutlookFocusedInbox", label: "Get Outlook Focused Inbox", description: "Get the doctor's Outlook focused inbox settings" },
  { name: "listOutlookCategories", label: "List Outlook Categories", description: "List the doctor's Outlook categories" },
  { name: "createOutlookCategory", label: "Create Outlook Category", description: "Create a new Outlook category" },
  { name: "updateOutlookCategory", label: "Update Outlook Category", description: "Update an Outlook category" },
  { name: "deleteOutlookCategory", label: "Delete Outlook Category", description: "Delete an Outlook category" },
  { name: "applyOutlookCategories", label: "Apply Outlook Categories", description: "Apply categories to Outlook messages" },
  { name: "removeOutlookCategories", label: "Remove Outlook Categories", description: "Remove categories from Outlook messages" },
  { name: "readOutlookCalendar", label: "Read Outlook Calendar", description: "Read events from the doctor's Outlook calendar" },
  { name: "createOutlookEvent", label: "Create Outlook Calendar Event", description: "Create an Outlook calendar event (may invite attendees)" },
  { name: "getOutlookEvent", label: "Get Outlook Calendar Event", description: "Get a single Outlook calendar event" },
  { name: "updateOutlookEvent", label: "Update Outlook Calendar Event", description: "Update an Outlook calendar event" },
  { name: "deleteOutlookEvent", label: "Delete Outlook Calendar Event", description: "Delete an Outlook calendar event" },
  { name: "searchOneDrive", label: "Search OneDrive", description: "Search for files in the doctor's OneDrive" },
  { name: "searchOneDriveAll", label: "Search OneDrive All", description: "Search all the doctor's OneDrive and SharePoint files" },
  { name: "listOneDriveItems", label: "List OneDrive Items", description: "List files and folders in the doctor's OneDrive" },
  { name: "getOneDriveItem", label: "Get OneDrive Item", description: "Get a single file or folder from OneDrive" },
  { name: "readOneDriveFile", label: "Read OneDrive File", description: "Read the content of a file in OneDrive" },
  { name: "downloadOneDriveFile", label: "Download OneDrive File", description: "Download a file from OneDrive" },
  { name: "uploadOneDriveFile", label: "Upload OneDrive File", description: "Upload a file to OneDrive" },
  { name: "deleteOneDriveItem", label: "Delete OneDrive Item", description: "Delete a file or folder from OneDrive" },
  { name: "shareOneDriveItem", label: "Share OneDrive Item", description: "Create a sharing link for a OneDrive file or folder" },
  { name: "moveOneDriveItem", label: "Move OneDrive Item", description: "Move a file or folder in OneDrive" },
  { name: "copyOneDriveItem", label: "Copy OneDrive Item", description: "Copy a file or folder in OneDrive" },
  { name: "createOneDriveFolder", label: "Create OneDrive Folder", description: "Create a new folder in OneDrive" },
  { name: "searchM365", label: "Search Microsoft 365", description: "Unified search across Outlook, OneDrive, and people" },
  { name: "listOutlookContacts", label: "List Outlook Contacts", description: "List the doctor's Outlook contacts" },
  { name: "searchOutlookContacts", label: "Search Outlook Contacts", description: "Search the doctor's Outlook contacts" },
  { name: "getOutlookContact", label: "Get Outlook Contact", description: "Get a single Outlook contact by ID" },
  { name: "createOutlookContact", label: "Create Outlook Contact", description: "Create a new Outlook contact" },
  { name: "updateOutlookContact", label: "Update Outlook Contact", description: "Update an Outlook contact" },
  { name: "deleteOutlookContact", label: "Delete Outlook Contact", description: "Delete an Outlook contact" },
  { name: "listOutlookContactFolders", label: "List Outlook Contact Folders", description: "List the doctor's Outlook contact folders" },
  { name: "createOutlookContactFolder", label: "Create Outlook Contact Folder", description: "Create a new Outlook contact folder" },
  { name: "listTodoLists", label: "List To Do Lists", description: "List the doctor's Microsoft To Do lists" },
  { name: "createTodoList", label: "Create To Do List", description: "Create a new Microsoft To Do list" },
  { name: "getTodoList", label: "Get To Do List", description: "Get a single Microsoft To Do list by ID" },
  { name: "updateTodoList", label: "Update To Do List", description: "Rename a Microsoft To Do list" },
  { name: "deleteTodoList", label: "Delete To Do List", description: "Delete a Microsoft To Do list" },
  { name: "listTodoTasks", label: "List To Do Tasks", description: "List tasks in a Microsoft To Do list" },
  { name: "createTodoTask", label: "Create To Do Task", description: "Create a task in a Microsoft To Do list" },
  { name: "getTodoTask", label: "Get To Do Task", description: "Get a single task from a Microsoft To Do list" },
  { name: "updateTodoTask", label: "Update To Do Task", description: "Update a task in a Microsoft To Do list" },
  { name: "deleteTodoTask", label: "Delete To Do Task", description: "Delete a task from a Microsoft To Do list" },
  { name: "listTodoChecklist", label: "List To Do Checklist", description: "List the checklist items of a Microsoft To Do task" },
  { name: "addTodoChecklistItem", label: "Add To Do Checklist Item", description: "Add a checklist item to a Microsoft To Do task" },
  { name: "updateTodoChecklistItem", label: "Update To Do Checklist Item", description: "Update a checklist item on a Microsoft To Do task" },
  // Automation
  { name: "scheduleTask", label: "Schedule Task", description: "Schedule a recurring or one-off automation task" },
  { name: "createEventTrigger", label: "Create Event Trigger", description: "Create an event trigger for automation" },
];